[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    links2004/WebSockets@^2.6.1
build_flags =
    -std=gnu++17
build_unflags =
    -std=gnu++11
